name: Docker Image CI/CD (Test Branch)

on:
  push:
    branches: [ "test" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'userscripts/**'
      - '.gitignore'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/docker-publish-test.yml'

env:
  REGISTRY_GHCR: ghcr.io
  IMAGE_NAME: y2a-auto

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_GHCR }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for GHCR
      id: meta-ghcr
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY_GHCR }}/fqscfqj/y2a-auto
        tags: |
          type=raw,value=test

    - name: Build and push Docker image (linux/amd64 only)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta-ghcr.outputs.tags }}
        labels: ${{ steps.meta-ghcr.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDTIME=${{ fromJSON(steps.meta-ghcr.outputs.json).labels['org.opencontainers.image.created'] }}
          VERSION=test-${{ github.sha }}
          REVISION=${{ fromJSON(steps.meta-ghcr.outputs.json).labels['org.opencontainers.image.revision'] }}

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Test GHCR test image
      run: |
        # 测试 GHCR test镜像启动
        docker run --rm -d --name test-y2a-auto-test \
          -p 5000:5000 \
          ghcr.io/fqscfqj/y2a-auto:test
        
        # 等待应用启动
        sleep 30
        
        # 测试健康检查
        curl -f http://localhost:5000/ || exit 1
        
        # 检查 yt-dlp 是否可用
        docker exec test-y2a-auto-test yt-dlp --version || exit 1
        
        # 清理
        docker stop test-y2a-auto-test